export const PATHS = {
  ROOT: '/',
  NEWS: '/news',
  PRODUCT_DESIGN: '/product-design',
  CO_BRANDING: '/co-branding',
  CONTACT: '/contact',
  MICROPHONES: '/microphones',
  SPEAKERS: '/speakers',
  SONIQUE: '/sonique',
  AUDIOWORX: '/audioworx',
  AUDIOEFX: '/audioefx',
  OVERVIEW: '/overview',
  TEAM: '/team',
  SEARCH: '/search/:query?',
  CLARI_VOICE: "/clarivoice",
  KOHLER: '/blogs-kohler',
  XIAOMI: '/blogs-xiaomi',
  ICONAI: '/blogs-iconai',
  CARDO: '/blogs-cardo',
  BYLINE: "/blogs-byline",
  SENA: "/blogs-sena",
  LOVESAC: "/blogs-lovesac"
};

export const EXTERNAL_PATHS = {
  LINKEDIN: 'https://linkedin.com/company/harman-embedded-audio',
  YOUTUBE: 'https://www.youtube.com/channel/UCrk41zGATZb3iZDHi6OpCCA',
  COOKIES: 'https://www.harman.com/cookies-statement',
  PRIVACY: 'https://www.harman.com/privacy-policy',
  TERMS_OF_USE: 'https://www.harman.com/terms-use',
  HARMAN: 'https://www.harman.com/',
  CARREERS: 'https://www.harman.com/careers',
  KOHLER_MOXIE: 'https://www.kohler.com/moxie',
  KOHLER_CNET: 'https://www.cnet.com/home/smart-home/kohler-moxie-showerhead-review-alexa-is-a-good-shower-caddy/',
  XIAOMI_OVERVIEW: 'https://www.mi.com/global/product/mi-11/overview',
  CARDO_WEBSITE: 'https://www.cardosystems.com',
  CARDO_FACEBOOK: 'https://www.facebook.com/CardoSystemsGlobal/',
  CARDO_TWITTER: 'https://twitter.com/cardosystems',
  CARDO_INSTAGRAM: 'https://www.instagram.com/cardosystems/',
}