export const videoContainer: string;
export const img: string;
export const gradient: string;
export const videoOverlay: string;
export const label: string;
export const sublabel: string;
export const play: string;
export const downArrow: string;
export const popupContainer: string;
