export const container: string;
export const sectionTitle: string;
export const contentContainer: string;
export const imageContainer: string;
export const image: string;
export const content: string;
export const title: string;
export const bullets: string;
export const bullet: string;
